const preguntasAlcoholes = [
  {
    id: "Alcohol01",
    topic: "Alcoholes",
    opciones: ["2,3-propanodial", "2,3-propanodiol", "1,2-propanodiol"],
    answer: 2,
    imagen: "https://www.alonsoformula.com/organica/images/alcoho101.gif",
  },
  {
    id: "Alcohol02",
    topic: "Alcoholes",
    opciones: ["3-butanol", "2-butanol", "3-butanal"],
    answer: 1,
    imagen: "https://www.alonsoformula.com/organica/images/alcoho102.gif",
  },
  {
    id: "Alcohol03",
    topic: "Alcoholes",
    opciones: ["1,2,3-butanotriol", "2,3,4-butanotriol", "1,2,3-butanotirol"],
    answer: 0,
    imagen: "https://www.alonsoformula.com/organica/images/alcoho103.gif",
  },
  {
    id: "Alcohol04",
    topic: "Alcoholes",
    opciones: ["2,4-hexanol", "2,4-hexanodiol", "3,5-hexanodiol"],
    answer: 1,
    imagen: "https://www.alonsoformula.com/organica/images/alcoho104.gif",
  },
  {
    id: "Alcohol05",
    topic: "Alcoholes",
    opciones: [
      "2-metil-1,3-pentanodiol",
      "2-metil-3,5-pentanodiol",
      "4-metil-1,3-pentanodiol",
    ],
    answer: 2,
    imagen: "https://www.alonsoformula.com/organica/images/alcoho105.gif",
  },
  {
    id: "Alcohol06",
    topic: "Alcoholes",
    opciones: ["4-penten-2-ol", "1-penten-4-ol", "2-pentenol"],
    answer: 0,
    imagen: "https://www.alonsoformula.com/organica/images/alcoho106.gif",
  },
  {
    id: "Alcohol07",
    topic: "Alcoholes",
    opciones: [
      "4-propil-2-penten-5-ol",
      "2-propil-3-penten-1-ol",
      "4-propil-3-penten-1-ol",
    ],
    answer: 1,
    imagen: "https://www.alonsoformula.com/organica/images/alcoho107.gif",
  },
  {
    id: "Alcohol08",
    topic: "Alcoholes",
    opciones: ["1,4-bencenodiol", "1,4-ciclohexanol", "1,4-ciclohexanodiol"],
    answer: 2,
    imagen: "https://www.alonsoformula.com/organica/images/alcoho108.gif",
  },
  {
    id: "Alcohol09",
    topic: "Alcoholes",
    opciones: [
      "2,6-ciclooctadien-1,5-diol",
      "1,5-ciclooctadien-3,7-diol",
      "1,5-ciclooctadien-4,8-diol",
    ],
    answer: 0,
    imagen: "https://www.alonsoformula.com/organica/images/alcoho109.gif",
  },
  {
    id: "Alcohol10",
    topic: "Alcoholes",
    opciones: [
      "1,3-ciclohexadien-5-ol",
      "2,4-ciclohexadien-1-ol",
      "3,5-ciclohexadien-1-ol",
    ],
    answer: 1,
    imagen: "https://www.alonsoformula.com/organica/images/alcoho110.gif",
  },
  {
    id: "Alcohol11",
    topic: "Alcoholes",
    opciones: ["2,3-butanol", "2,3-butanodiol", "2,3-butanodial"],
    answer: 1,
    imagen: "https://www.alonsoformula.com/organica/images/alcoho11.gif",
  },
  {
    id: "Alcohol12",
    topic: "Alcoholes",
    opciones: ["2-butan-1-ol", "2-buten-1-al", "2-buten-1-ol"],
    answer: 2,
    imagen: "https://www.alonsoformula.com/organica/images/alcoho13.gif",
  },
  {
    id: "Alcohol13",
    topic: "Alcoholes",
    opciones: ["3-penten-2-ol", "3-pentenol-2", "3-pentin-2-ol"],
    answer: 0,
    imagen: "https://www.alonsoformula.com/organica/images/alcoho15.gif",
  },
  {
    id: "Alcohol14",
    topic: "Alcoholes",
    opciones: ["5-hexin-3-en-1-ol", "3-hexen-1-in-6-ol", "3-hexen-5-in-1-ol"],
    answer: 2,
    imagen: "https://www.alonsoformula.com/organica/images/alcoho17.gif",
  },
  {
    id: "Alcohol15",
    topic: "Alcoholes",
    opciones: [
      "1,2,3-propanol o glicerina",
      "1,2,3-propanotriol o glicerina",
      "1,2,3-propanotrial o glicerina",
    ],
    answer: 1,
    imagen: "https://www.alonsoformula.com/organica/images/alcoho19.gif",
  },
  {
    id: "Alcohol16",
    topic: "Alcoholes",
    opciones: [
      "4-metil-2,5-pentanodiol",
      "2-metil-1,4-pentanodiol",
      "2,4-dimetil-1,4-butanodiol",
    ],
    answer: 1,
    imagen: "https://www.alonsoformula.com/organica/images/alcoho12.gif",
  },
  {
    id: "Alcohol17",
    topic: "Alcoholes",
    opciones: ["1,2-ciclohexanodiol", "1,2-bencenodiol", "1,2-ciclohexanol"],
    answer: 0,
    imagen: "https://www.alonsoformula.com/organica/images/alcoho14.gif",
  },
  {
    id: "Alcohol18",
    topic: "Alcoholes",
    opciones: [
      "1-ciclohexen-3,5-diol",
      "1-ciclohexen-4,6-diol",
      "4-ciclohexen-1,3-diol",
    ],
    answer: 2,
    imagen: "https://www.alonsoformula.com/organica/images/alcoho16.gif",
  },
  {
    id: "Alcohol19",
    topic: "Alcoholes",
    opciones: [
      "2,3-dietilciclohexanol",
      "1,2-dietilciclohexanol",
      "1,2-dietilciclohexan-3-ol",
    ],
    answer: 0,
    imagen: "https://www.alonsoformula.com/organica/images/alcoho18.gif",
  },
  {
    id: "Alcohol20",
    topic: "Alcoholes",
    opciones: ["2-ciclopentenol", "1-ciclopentenol", "1-ciclopenten-2-ol"],
    answer: 1,
    imagen: "https://www.alonsoformula.com/organica/images/alcoho20.gif",
  }
];

export default preguntasAlcoholes;
